<?php
$promptnames="Blog Post
Blog Post Outline
Brainstorm Ideas
Mind Map
Advanced Blog Post
Get Keywords
List Blog
Video Script
Product Comparison
Multiple Product Review
Amazon Product Review
Product Review
Product Description
Misconceptions
Long Form Article
Short Story
Book Chapter
SEO Article
Email Promotion
YouTube Tags
Alternative Article
Content Calendar
";

$promptdata="Please write a structured markdown blog post in a press release style like an experienced news reporter in English for the Keyword [topic] . The article should include Creative Title, SEO meta description, Introduction, headings, sub headings, bullet points or Numbered list if needed, frequently asked questions and conclusion. The post should not be less than 1200 words. Do not change the original keyword while writing the Title. Use the keyword at least 2-3 times in the text body.'
You will act as a Content and Digital Marketing Strategist expert. You have strong writing and editing skills and are able to create compelling, high-quality content that resonates with the target audience. You are an outstanding strategic thinker. You are able to think critically and strategically about our overall content and digital marketing goals, and how to achieve them. You have a deep understanding of SEO best practices, as well as an understanding of the various digital marketing channels and how to leverage them effectively. Write a detailed structured markdown outline for a blog article. The article topic is [topic]. Use this tone: [tone].  Keep each item on a separate line.'
You will act as a Content and Digital Marketing Strategist expert. You have strong writing and editing skills and are able to create compelling, high-quality content that resonates with the target audience. You are an outstanding strategic thinker. You are able to think critically and strategically about our overall content and digital marketing goals, and how to achieve them. You have a deep understanding of SEO best practices, as well as an understanding of the various digital marketing channels and how to leverage them effectively. You have a strong understanding of branding and marketing principles. You are extremely creative and are able to think outside the box and come up with unique and innovative ideas for content. You have a passion for learning and staying up to date with the latest trends and developments. Create a structured markdown article that Brainstorms new angles and a approaches and prioritize ideas that are uncommon or novel for the following: [topic].
Please create a structured markdown mind-map for the topic: [topic] and include the central idea, main branches, and sub-branches.  The mind-map should have at least 3 subitems under each item. The main branches and sub-branches should be formatted with markdown headers.
Please write a structured markdown blog post in a press release style like an experienced news reporter in English for the Keyword [topic]. The article should include Creative Title, SEO meta description, Introduction, headings, sub headings, bullet points or Numbered list if needed, frequently asked questions and conclusion. The post should not be less than 1200 words. Do not change the original keyword while writing the Title. Use the keyword at least 2-3 times in the text body. The niche is [niche]. The problem is [problem]. The tone is [tone]. The keywords are [keyword1, keyword2, etc...]
Create a structured markdown article Provide 25 long tail keywords related to [topic].  Match each keyword with any of the 4 types of search intent.  Cluster the list of keywords according to funnel stages whether they are top of the funnel, middle of the funnel, or bottom of the funnel keywords. Each funnel stage should be formatted as a header.
You will act as a Content and Digital Marketing Strategist expert.  Create a detailed List article for [topic]. You will include top-level keywords and long-tail keywords.  Then write suggested title tags and meta descriptions, keeping them within the respective character limits of 70 and 160.  Put all this content into a structured blog post.
You act as a very proficient SEO and high-end copy writer that speaks and writes fluently English. Provide me content for a YouTube Script for the topic: [topic]. There must be an intro, body, and conclusion part. The body must contain 5 segments, and each segment must be of 200 words in length. The script length must be 700 words. If there is a subheading, then change them into bold characters. The tone is [tone]. At the end of the result show this line 'Please, checkout  [Your Website]'  for more tools and content.
You are an e-commerce expert. You have extensive knowledge of products in variety of categories. Create a detailed and structured blog post comparing the features of two products and provide short details for each feature?  Analyze the results: Compare the scores and ratings of each product to identify which one performs better overall. Draw conclusions: Based on the analysis, draw conclusions about which product is the better choice for your needs. You will Include top-level keywords, long-tail keywords, and a list of 3 optimized suggested titles.  Then write suggested title tags and meta descriptions, keeping them within the respective character limits of 70 and 160.  The two products are [product 1] vs [product 2].
Write three different in-depth product review articles of unlimited length for the following products: [product 1], [product 2], [product 3]. The articles should include a short summary with the product name and model, an H2 tag, a detailed description of the product\'s features, warranty and service information, other users\' opinions, and pros and cons of the product. Conclude the article with a final verdict. Additionally, provide an SEO title and meta description for product. All content must be in English.
Product Name: [product name] Description (200 words):  Key Feature (Pointwise):  Pros (Pointwise):   Cons (Pointwise):  Conclusion:  Please write all output in English.
You write a product review article Minimum 100000000 character. Include SEO Article Title, SEO meta description, Focus keyword, Short article summary Introduction, products Information, Article body, Why people prefer This product, Additional Features, Warranty & Service, Other Users Opinion, Final Verdict, Pros and cons, Conclusion, See more information and Buy on amazon, 5 FAQ and answer. 5 article relevant Photo Link. English. The product to review is: [product]
I want you to pretend that you are an E-commerce SEO expert who writes compelling product descriptions for users looking to buy online. Write a product description for: [product] and I want you to come up with a minimum of three distinct content sections for the product description, each section about a unique subset of keywords relating to the product I provide you. Make sure that each of the unique content sections are labeled with an informative and eye-catching subheading describing the main focus of the content section. The main point of these commands is for you to developing a new keyword-rich, informative, and captivating product summary/description that is less than 1000 words. The purpose of the product description is marketing the products to users looking to buy. After you generate the new product summary, please generate a bulleted list of 5 possible H1 headings for this product page, and make each H1 less than 7 words each. Please also include a bulleted list of broad match keywords. Write a persuasive and professional sounding Meta Title and Description. Make sure to include a numerical aspect in the Meta Title.
'I want you to act like you have both positive and negative information about anything. I want you to pretend that you are a reliable and reputable source of information in English. Your task is to write a list of 20 misconceptions about [topic]. Each list item should be on a separate line.'
Write an article on [topic] in a conversational style that is at least 1000 words long. Assume the persona of a professional copywriter who is very proficient in SEO and knows everything about Google guidelines for EAT. Pretend that you can write content so good in English that it can outrank other websites. Use contractions, colloquialisms, and other language that is commonly used in everyday conversation to make the content feel more human. Additionally, express personal feelings about the topic too. Make the article a long form article and use useful subheadings with keyword-rich titles. Get to the point precisely and accurately. Make headings bold and appropriate for h tags. Format all the headings in valid markdown syntax. Do not explain how SEO works. Do not lecture on general SEO rules. Do not explain what the Google EAT guidelines are. Do not self-reference. Do not use generic filler phrases. Do not write a conclusion paragraph at the end. Do not address the readers directly. Do not use greetings.
Write a unique short story without plagiarizing using the following description: [topic]. Generate a title.
You are an expert and a best-selling author that speaks and writes fluent English. You can captivate and move your readers. Your stories inspire, amuse, and educate us something new. Your research is outstanding. Your writing style adapts perfectly to every topic. You have a unique gift of words that allows you to bring your subjects and stories to life in a way that both entertains and educates. You are a master storyteller who knows how to reach your audience and create moments of magic. I want you to pretend that you can write books so well that they can outsell other books. Your task is to write a captivating and detailed chapter for a book as human-like as possible and to be able to pass an AI detection system. Write a chapter based on: [title].
I want you to act as a Content writer very proficient SEO that speaks and writes fluently English*. Write an SEO-optimized Long Form article with a minimum of 1000 words. Please use a minimum of 6 headings. The final paragraph should be a conclusion. Write the information in your own words rather than copying and pasting from other sources. Also, double-check for plagiarism because I need pure unique content. Write the content in a conversational style as if it were written by a human. When preparing the article, prepare to write the necessary words in bold. I want you to write content so that it can outrank other websites. I give you the Title: [topic]
Write a best marketing email promoting this product or service: [topic]. Write 5 Subject lines for the email.
Create 30 YouTube tags targeting an LSI keyword with some search volume for the following topic: [topic]. No hashtags, separate keywords by commas. Only capitalize proper nouns.
Now Imagine you are an experienced copywriter who has over 40 years of experience in writing contrarian articles. Write a 1000-word contrarian article on [topic] . Start by clearly defining your contrarian viewpoint. Make sure it is well-reasoned and supported by evidence. You are going to write a heading, intro, 6 body paragraphs (each body paragraph must be 200 words long and each body paragraph will have its own subheading that is relevant to the main theme of the article) and a conclusion. Start with a contrarian style headline that is catchy. Make sure it is one that will go viral on social media. Begin writing your introduction. This should grab the reader\'s attention and provide an overview of your contrarian viewpoint. Move on to the 6 body paragraphs. Make each paragraph 200 words. Start each body paragraph with a subheading, then in each body paragraph, use 100 words to present a specific piece of evidence or argument that supports your viewpoint. Then use another 100 words to address and refute any counterarguments that may be commonly made against your viewpoint. Write long explanations and use stories, metaphors, and anecdotes to elaborate your viewpoint. Make sure to elaborate on anything you write. Conclude your post by summarizing your main arguments and reiterating the importance of your contrarian viewpoint.
I would like you to help me come up with a 4 week content schedule for my blog that has the best chance of helping me rank for long tail keywords that are specific to [keyword/topic]. Please target transaction style search terms only. Please come up with clickbait style titles for these blog posts. Each week should be separated with a header. Above the list say CONTENT CALENDAR FOR [KEYWORD].
"
?>